package MEDISCAN.MEDI.service;

import MEDISCAN.MEDI.model.QRReport;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;

@Service
public class PdfService {

    public byte[] generatePdfForReport(QRReport report) {
        try {
            Document document = new Document();
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, baos);
            document.open();

            // Fonts
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 14);

            // Title
            Paragraph title = new Paragraph("Medical Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);
            document.add(Chunk.NEWLINE);

            // Patient Info
            document.add(new Paragraph("Patient Details", sectionFont));
            document.add(new Paragraph("Patient Name: " + report.getName(), normalFont));
            document.add(new Paragraph("User ID: " + report.getUserId(), normalFont));
            document.add(new Paragraph("Report URL: " + report.getReportUrl(), normalFont));
            document.add(Chunk.NEWLINE);

            // Diagnosis
            document.add(new Paragraph("Diagnosis", sectionFont));
            document.add(new Paragraph(report.getDiagnosis() != null ? report.getDiagnosis() : "Not Provided", normalFont));
            document.add(Chunk.NEWLINE);

            // Treatment
            document.add(new Paragraph("Treatment Process", sectionFont));
            document.add(new Paragraph(report.getTreatment() != null ? report.getTreatment() : "Not Provided", normalFont));
            document.add(Chunk.NEWLINE);

            // Prescriptions
            document.add(new Paragraph("Prescriptions", sectionFont));
            document.add(new Paragraph(report.getPrescriptions() != null ? report.getPrescriptions() : "Not Provided", normalFont));
            document.add(Chunk.NEWLINE);

            // Doctor Notes
            document.add(new Paragraph("Doctor Notes", sectionFont));
            document.add(new Paragraph(report.getDoctorNotes() != null ? report.getDoctorNotes() : "Not Provided", normalFont));
            document.add(Chunk.NEWLINE);

            // Footer
            document.add(new Paragraph("Generated by MediScan", normalFont));

            document.close();
            return baos.toByteArray();

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }
}
